name: Make submission

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: /usr/share/rust/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Cache debug build result
        uses: actions/cache@v2
        with:
          path: target/debug
          key: ${{ runner.os }}-build-debug-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-debug-
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
  build:
    name: Build the solution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: /usr/share/rust/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Cache release build result
        uses: actions/cache@v2
        with:
          path: target/release
          key: ${{ runner.os }}-build-release-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-release-
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: submission
          path: target/release/submission
  push:
    name: Push to the submission branch
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout submission branch
        uses: actions/checkout@v2
        with:
          ref: submission
          fetch-depth: 0
      - name: Download build result
        uses: actions/download-artifact@v1
        with:
          name: submission
          path: target/release
      - name: Cleanup build result
        uses: geekyeggo/delete-artifact@v1
        with:
          name: submission
      - name: Push submission
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add target/release/submission
          git commit -am "Add submission $GITHUB_SHA" && git push || echo "Ignoring"
        env:
          DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
